#!/usr/bin/env python3

from optparse import OptionParser
from sqs import sqs
from logs.log import logger


if __name__ == '__main__':
    parser = OptionParser()
    parser.add_option("--sqs-queue-url",
                      dest="sqs_queue_url",
                      help="SQS Queue URL")
    parser.add_option("--kubernetes-deployment",
                      dest="kubernetes_deployment",
                      help="")
    parser.add_option("--kubernetes-namespace",
                      dest="kubernetes_namespace",
                      help="")
    parser.add_option("--aws-region",
                      dest="aws_region",
                      help="")
    parser.add_option("--poll-period",
                      dest="poll_period",
                      type="int",
                      default=10,
                      help="")
    parser.add_option("--scale-down-cool-down",
                      dest="scale_down_cool_down",
                      type="int",
                      default=30,
                      help="")
    parser.add_option("--scale-up-cool-down",
                      dest="scale_up_cool_down",
                      type="int",
                      default=10,
                      help="")
    parser.add_option("--scale-up-messages",
                      dest="scale_up_messages",
                      type="int",
                      default=20,
                      help="")
    parser.add_option("--scale-down-messages",
                      dest="scale_down_messages",
                      type="int",
                      default=10,
                      help="")
    parser.add_option("--max-pods",
                      dest="max_pods",
                      type="int",
                      default=10,
                      help="")
    parser.add_option("--min-pods",
                      dest="min_pods",
                      type="int",
                      default=1,
                      help="")

    (options, args) = parser.parse_args()

    if not options.sqs_queue_url:
        parser.error('SQS_QUEUE_URL not given')
    if not options.kubernetes_deployment:
        parser.error('KUBERNETES_DEPLOYMENT not given')
    if not options.aws_region:
        parser.error('AWS_REGION not given')
    if not options.kubernetes_namespace:
        parser.error('KUBERNETES_NAMESPACE not given')
    if not options.kubernetes_deployment:
        parser.error('KUBERNETES_DEPLOYMENT not given')
    logger.debug(options)
    sqs.run(options)
